-- black list
return {
   '123rf',
   'africaimagery',
   'airpics',
   'arkive',
   'bigstock',
   'business images',
   'camstock',
   'canstockphoto',
   'chinese-fashion',
   'clip art of',
   'clipartof',
   'colour box',
   'colourbox',
   'cutcaster',
   'depositphotos',
   'dollarphotoclub',
   'dreamstime',
   'dreamstime',
   'envato',
   'fotolia',
   'fotolibra',
   'getty',
   'graphic-leftovers',
   'graphicleftovers',
   'graphics factory',
   'illlustration of',
   'istock',
   'justjared',
   'keyimagery',
   'masterfile',
   'masterfile',
   'photobucket',
   'photoexpress',
   'sample text',
   'sciencephoto',
   'sciencephotoimage',
   'shutterstock',
   'toonvectors',
   'visualphotos',
   'yoy'
}
